function chinesechecker(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',zc='.cache.html',db='/',pb='//',fc='0A70BA5DC2030F1A3D55883B7203AEC0',gc='17FF9D4ADCEAA017A6276AECB1A724C2',hc='248ED0F2AA43DF5BFC69B72C7FB617BB',ic='35F8480D62063A37651EFEE75CBAA5C5',jc='3D8EE94A21A8D7F0EA79382AB56F6484',kc='5ECA9EFB53D6EEDE7191816F1827FCD8',lc='60E82F3D21CBEB1F9F6D21BAB35C20C1',mc='832315BCA469625EB70E9FA617A5DA9F',nc='8B711D32E6CCC696326A2FD90D6A6384',oc='9C8C34198009BF779EDDBDF3CD3C5776',pc='9DFB29EF42A09FEB65874584E7BAC8F4',yc=':',tb='::',Hc='<script defer="defer">chinesechecker.onInjectionDone(\'chinesechecker\')<\/script>',lb='<script id="',wb='=',cb='?',qc='A8F0BFC9543DF9E0B9A2FC15F77ACB14',rc='B1A38994BA132BDE8FEFD68BF385C754',sc='BBFBFDAE1C701534BCEE67DCC6D7E779',yb='Bad handler "',tc='CB6CDFC412A715B01D8026F4BBD17424',uc='D4A0867F143E6F53E32735C91B498A7C',Gc='DOMContentLoaded',vc='E7AC8746314FC18A0AD0283508EF2668',wc='F321F60D94DEC0F63297544A6F513864',xc='F9D7FBED326CF447590DEFD8EE46A786',nb='SCRIPT',kb='__gwt_marker_chinesechecker',Hb='android',Jb='android_tablet',ob='base',gb='baseUrl',X='begin',Pb='blackberry',W='bootstrap',U='chinesechecker',ib='chinesechecker.nocache.js',sb='chinesechecker::',fb='clear.cache.gif',vb='content',Qb='desktop',ab='end',_b='gecko',ac='gecko1_8',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',Ac='gwt/clean/clean.css',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',Fc='head',dc='hosted.html?chinesechecker',Ec='href',Yb='ie10',$b='ie8',Zb='ie9',Cb='iframe',eb='img',Kb='ipad',Lb='ipad_retina',Mb='iphone',Nb='ipod',Db="javascript:''",Bc='link',cc='loadExternalRefs',qb='meta',Gb='mgwt.os',Ib='mobile',Rb='mobile.user.agent',Sb='mobilesafari',Fb='moduleRequested',_='moduleStartup',Xb='msie',rb='name',Tb='not_mobile',Eb='position:absolute;width:0;height:0;border:none',Cc='rel',Ob='retina',Wb='safari',hb='script',ec='selectingPermutation',V='startup',Dc='stylesheet',jb='undefined',bc='unknown',Ub='user.agent',Vb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}chinesechecker=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=J(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a){var b=u[a];return b==null?null:b}
function K(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Hb)!=-1){if(a.indexOf(Ib)!=-1){return Hb}else{return Jb}}if(a.indexOf(Kb)!=-1){if(window.devicePixelRatio>=2){return Lb}return Kb}if(a.indexOf(Mb)!=-1||a.indexOf(Nb)!=-1){if(window.devicePixelRatio>=2){return Ob}return Mb}if(a.indexOf(Pb)!=-1){return Pb}return Qb}();return b}};v[Gb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};w[Rb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Sb:Tb};v[Rb]={mobilesafari:0,not_mobile:1};w[Ub]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Vb)!=-1}())return Wb;if(function(){return b.indexOf(Xb)!=-1&&n.documentMode>=10}())return Yb;if(function(){return b.indexOf(Xb)!=-1&&n.documentMode>=9}())return Zb;if(function(){return b.indexOf(Xb)!=-1&&n.documentMode>=8}())return $b;if(function(){return b.indexOf(_b)!=-1}())return ac;return bc};v[Ub]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};chinesechecker.onScriptLoad=function(){if(M){r=true;G()}};chinesechecker.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:cc,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=dc;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ec});if(!F()){try{K([Lb,Sb,Wb],fc);K([Kb,Tb,Wb],gc);K([Jb,Sb,Wb],hc);K([Pb,Tb,Wb],ic);K([Kb,Sb,Wb],jc);K([Ob,Sb,Wb],kc);K([Lb,Tb,Wb],lc);K([Qb,Tb,$b],mc);K([Pb,Sb,Wb],nc);K([Qb,Tb,Wb],oc);K([Jb,Tb,Wb],pc);K([Qb,Tb,Zb],qc);K([Mb,Tb,Wb],rc);K([Ob,Tb,Wb],sc);K([Hb,Tb,Wb],tc);K([Mb,Sb,Wb],uc);K([Qb,Tb,ac],vc);K([Qb,Sb,Wb],wc);K([Hb,Sb,Wb],xc);O=A[L(Gb)][L(Rb)][L(Ub)];var Q=O.indexOf(yc);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+zc}catch(a){return}}var R;function S(){if(!s){s=true;if(!__gwt_stylesLoaded[Ac]){var a=n.createElement(Bc);__gwt_stylesLoaded[Ac]=a;a.setAttribute(Cc,Dc);a.setAttribute(Ec,t+Ac);n.getElementsByTagName(Fc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(Gc,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener(Gc,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:cc,millis:(new Date).getTime(),type:X});n.write(Hc)}
chinesechecker();